### PR TITLE
Move Lambdacomponents to aws-otel-lambda

### PR DESCRIPTION
**Pull request by Kausik-A**
**Description:** 

This PR is in pair with https://github.com/aws-observability/aws-otel-lambda/pull/481 which moves over the lambdacomponents module from [aws-otel-collector](https://github.com/aws-observability/aws-otel-collector) to [aws-otel-lambda](https://github.com/aws-observability/aws-otel-lambda)

**Testing:** 

Built the collector layer locally.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by erichsueh3 — APPROVED** [review]
LGTM let's make sure that any changes to the lambda release process is captured as well

**Review by vasireddy99 — APPROVED** [review]

**Comment by Kausik-A** [comment]
`lambdacomponents` were introduced inside `aws-otel-lambda` as part of this [PR](https://github.com/aws-observability/aws-otel-lambda/pull/492) and show [successful run](https://github.com/aws-observability/aws-otel-lambda/actions/runs/4380077052) of the integration tests. Merging this PR now

**Comment by rapphil** [comment]
@Aneurysm9 was suggesting to add a deprecation warning first before removing altogether.

**Comment by rapphil** [comment]
Here are instructions for deprecating https://go.dev/ref/mod#go-mod-file-module-deprecation

**Review by bryan-aguilar — APPROVED** [review]

**Comment by bryan-aguilar** [comment]
Closed in favor of https://github.com/aws-observability/aws-otel-collector/pull/1981

**Pull request closed without merging**
