### PR TITLE
Add tail sampling to ADOT

### PR DESCRIPTION
**Pull request by ElementalWarrior**
Adding tailsampling processor from opentelemetry contrib

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bryan-aguilar** [comment]
Hi @ElementalWarrior,

While we appreciate the PR we currently do not accept PRs for new components at the moment.

**Comment by ElementalWarrior** [comment]
@bryan-aguilar its not really a new component, its just one of the standard processors from the original opentelemetry-collector repo. 

Is there some rationale it wasn't included in the first place?

Tail sampling is one of the few ways you can drop specific spans by chaining the attributes processor with tail sampling.

**Comment by ElementalWarrior** [comment]
Or perhaps do you have a time frame of when this processor will be added? I'd really rather not support a fork based off of ADOT.

**Comment by bryan-aguilar** [comment]
Thank you for your interest in expanding the functionality of the ADOT Collector.  Unfortunately, we cannot at this time accept PRs for new components.  As ADOT is a distribution that is fully supported by AWS we must ensure that all components included in the distribution are integrated in our support, testing, and security review processes.

If you can create a feature request issue we can use that signal to help prioritize the work needed to fully support this component as part of the ADOT Collector distribution.  Thanks!

**Pull request closed without merging**
