### PR TITLE
Removal of dedup docs

### PR DESCRIPTION
**Pull request by vasireddy99**
**Description:** 
This PR is created to remove the docs existing in the github repo in order to support the idea of maintaining at https://aws-otel.github.io/docs/introduction

**Link to tracking Issue:** #1485 

**Testing:** IRSA

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bryan-aguilar** [comment]
Can you provide some links to where these documents are duplicated on the website?

**Comment by vasireddy99** [comment]
yes, sure 
docs for EKS setup and usage : https://aws-otel.github.io/docs/setup/eks
docs for ECS setup and usage : https://aws-otel.github.io/docs/setup/ecs

**Comment by vasireddy99** [comment]
> yes, sure
> docs for EKS setup and usage : https://aws-otel.github.io/docs/setup/eks
> docs for ECS setup and usage : https://aws-otel.github.io/docs/setup/ecs

I am currently tweaking some changes to the documentation at these links. So would add that reference here and can go for the approval. Making it draft for now.

**Comment by vasireddy99** [comment]
PR for reference : https://github.com/aws-otel/aws-otel.github.io/pull/424/

**Comment by vasireddy99** [comment]
THis PR is ready for review for review.

**Review by PaurushGarg — APPROVED** [review]
LGTM

**Pull request merged**
