### PR TITLE
update OTel Collector deps to v0.22

### PR DESCRIPTION
**Pull request by mxiamxia**
**Description:** 
* Upgrade OTel Collector lib to the latest version (v 0.22)
* Fixed the breaking public API changes

**Link to tracking Issue:**
* https://github.com/aws-observability/aws-otel-collector/issues/391

**Testing:**
`make build`

### CODE REVIEW

**Comment by mxiamxia** [comment]
NewRelic Exporter failed on integration test after bumping up the version to v0.22. @alanwest

**Comment by alanwest** [comment]
> NewRelic Exporter failed on integration test after bumping up the version to v0.22. @alanwest

Thanks, @mxiamxia, I've pushed an update here https://github.com/aws-observability/aws-otel-test-framework/pull/240.

I believe this should be the fix, though I'm having trouble running the test suite locally. I can look at this closer tomorrow.

**Review by vastin — APPROVED** [review]

**Review by vastin — CHANGES_REQUESTED** [review]
Unit test failed
--- FAIL: TestGetCfgFactoryWithoutConfig (0.00s)

**Comment by a-feld** [comment]
@vastin I opened a separate PR [here](https://github.com/aws-observability/aws-otel-test-framework/pull/241)

**Comment by vastin** [comment]
@a-feld The unit test failure of TestGetCfgFactoryWithoutConfig is another issue which might be changes in pkg/config/config_factory_test.go

**Comment by mxiamxia** [comment]
@alanwest @a-feld , it looks NewRelic exporter is still failing from mock test. I am not sure how https://github.com/aws-observability/aws-otel-test-framework/pull/241 could be related. Could you please elaborate it a bit?

**Comment by a-feld** [comment]
A breaking change was introduced to the New Relic exporter in the latest release. HTTP path for the New Relic exporter cannot be overridden. All HTTP posts must be sent to a URL in the form of:
```
https://{host:port}/trace/v1
https://{host:port}/metric/v1
```

Since path is not configurable, the exporter cannot be configured to send data to the URL:
```
https://mocked-server/put-data
```

To fix the tests, the mock server has been updated to accept any path on the https port as data in https://github.com/aws-observability/aws-otel-test-framework/pull/241

The NR exporter is then configured to send data to:
```
https://mocked-server/trace/v1
https://mocked-server/metric/v1
```

**Review by vastin — APPROVED** [review]

**Pull request merged**
