### PR TITLE
Separate documentation sync from performance test runs.

### PR DESCRIPTION
**Pull request by jefchien**
**Description:** Moved documentation sync out of performance test workflow. They aren't related.

**Testing:** Runs the same commands as the existing performance test workflow.

### CODE REVIEW

**Review by sethAmazon — APPROVED** [review]

**Comment by khanhntd** [comment]
Should the ```document sync``` workflow be sync after the performance test if I understand the ```document sync``` workflow correctly: to sync the performance table into the main branch ?

**Comment by jefchien** [comment]
> Should the `document sync` workflow be sync after the performance test if I understand the `document sync` workflow correctly: to sync the performance table into the main branch ?

The document sync workflow is just to get the README and all other docs synced with the main branch. It has nothing to do with the performance tests or table, which is why I've separated it.

**Comment by khanhntd** [comment]
> > Should the `document sync` workflow be sync after the performance test if I understand the `document sync` workflow correctly: to sync the performance table into the main branch ?
> 
> The document sync workflow is just to get the README and all other docs synced with the main branch. It has nothing to do with the performance tests or table, which is why I've separated it. This is necessary because if only document changes are made, the CI doesn't run and the performance tests won't get triggered, so the docs on the gh-pages site won't be up to date.

Reasonable. Understanding more about the doc now though.

**Review by khanhntd — APPROVED** [review]
LGTM

**Pull request merged**
