### PR TITLE
Reproduce the bug for ECS container receiver

### PR DESCRIPTION
**Pull request by JohnWu20**
**Description:** 
Checking the bugs for this integration test error:
https://github.com/aws-observability/aws-otel-collector/runs/1779025519?check_suite_focus=true

### CODE REVIEW

**Comment by mxiamxia** [comment]
Only this specific commit works? does v0.18.0 work?

**Comment by JohnWu20** [comment]
> Only this specific commit works? does v0.18.0 work?

This is the newest version which I believe it is same with v.0.19.0.  Do you mean does v0.19.0 or v0.18.0 work?

**Comment by mxiamxia** [comment]
> > Only this specific commit works? does v0.18.0 work?
> 
> This is the newest version which I believe it is same with v.0.19.0. Do you mean does v0.19.0 or v0.18.0 work?

I revert

**Comment by JohnWu20** [comment]
> > > Only this specific commit works? does v0.18.0 work?
> > 
> > 
> > This is the newest version which I believe it is same with v.0.19.0. Do you mean does v0.19.0 or v0.18.0 work?
> 
> I reverted `awsecscontainermetricsreceiver` to v0.18.0 below, if it works, we'll release it in the next release.
> 
> github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver v0.18.0

v0.18.0 is the old version, and v0.19.0 will include some new metadata. I think both of them work well now.

**Comment by hossain-rayhan** [comment]
Interesting. If both of v0.18 and v0.19 work fine, let's merge them. Before that can we do the following, John
1. Create a separate Test PR with v0.19 and close the PR if it passes. Just to be confident.
2. Address our known issue with Fargate platform version 1.4 for new metadata.

**Comment by JohnWu20** [comment]
> Interesting. If both of v0.18 and v0.19 work fine, let's merge them. Before that can we do the following, John
> 
> 1. Create a separate Test PR with v0.19 and close the PR if it passes. Just to be confident.
> 2. Address our known issue with Fargate platform version 1.4 for new metadata.

Sure, thanks Rayhan, I will create a new pr to test v0.19 again. And I have scheduled a time tomorrow with Fargate team to discuss the new metadata things.

**Comment by wyTrivail** [comment]
I wonder why didn't we capture this issue in unit tests? Dimensions changing seems a big change which unit tests should validate it.

**Comment by hossain-rayhan** [comment]
> I wonder why didn't we capture this issue in unit tests? Dimensions changing seems a big change which unit tests should validate it.

which unit tests we are talking about. Dimension concepts are strictly true for `awsemf` exporter. The code change was made in the reveiver and I believe we had unit tests to validate the extra metadata we are adding as resource attributes. Am I missing something?

**Comment by wyTrivail** [comment]
> > I wonder why didn't we capture this issue in unit tests? Dimensions changing seems a big change which unit tests should validate it.
> 
> 
> 
> which unit tests we are talking about. Dimension concepts are strictly true for `awsemf` exporter. The code change was made in the reveiver and I believe we had unit tests to validate the extra metadata we are adding as resource attributes. Am I missing something?
> 
> 
> 
> Did you mean integration test validation logic in the testing framework?

I meant The unit test in receiver,can you point me to the code so I can better understand how do we validate the resource attributes?

**Comment by hossain-rayhan** [comment]
I think we identified the cause. There was a misunderstanding. We didn't update the expected metrics for the validation with new dimensions which we should.

**Comment by JohnWu20** [comment]
Thanks for the reminder, I will update the expected metrics in the test framework.

**Comment by mxiamxia** [comment]
we have code freeze now for the 2/1 release. The ecs metadata receiver v0.18.0 is included for this release because it is the one can pass the current Integ test.

**Pull request closed without merging**
