### PR TITLE
Add Dynatrace metric exporter

### PR DESCRIPTION
**Pull request by dyladan**
**Description:**

- Add Dynatrace metric exporter to AWS OpenTelemetry distro
- Add end to end tests following wiki description
- Add exporter to README list

**Link to tracking Issue:** n/a

**Testing:**

- Unit tests in [collector contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/dynatraceexporter) repository
- E2E tests pending merge https://github.com/aws-observability/aws-otel-test-framework/pull/104

Documentation:

- Added exporter to README list following example from Datadog
- [Usage documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/dynatraceexporter/README.md)

/cc @arminru

### CODE REVIEW

**Review by wyTrivail — APPROVED** [review]
thanks!

**Comment by mxiamxia** [comment]
Sorry, I merged the New Relic changes and caused another conflict here. Please help to resolve the conflict and I'll merge this PR. Thanks.

**Comment by arminru** [comment]
@mxiamxia No worries, I just merged the changes again. Thanks!

**Comment by arminru** [comment]
@mxiamxia @wyTrivail I think all merge conflicts are resolved now, let me know if you need anything else.

**Pull request merged**
