### PR TITLE
[release/v0.26.x] bump version to v0.26.2

### PR DESCRIPTION
**Pull request by PaurushGarg**
**Description:** <Describe what has changed.>
This PR bumps the version to v0.26.2

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bryan-aguilar — COMMENTED** [review]
Versions.txt also needs to be updated.

**Review by vasireddy99 — APPROVED** [review]

**Review by vasireddy99 — COMMENTED** [review]
oh looks like the https://github.com/aws-observability/aws-otel-collector/blob/release/v0.26.x/VERSION#L1 is already updated.

**Comment by bryan-aguilar** [comment]
Good catch.

**Review by bryan-aguilar — APPROVED** [review]

**Comment by PaurushGarg** [comment]
> `VERSION` also needs to be updated. It should be `v0.26.2`.

That was already updated by Anthony in previous commit to the release branch v0.26.2

**Pull request merged**
