### PR TITLE
Separate CodeQL analysis into own workflow.

### PR DESCRIPTION
**Pull request by jefchien**
**Description:** CodeQL slows down the PR process and re-runs on each PR update. Separated into its own workflow and set to only run on merges to `main` or `dev`.

### CODE REVIEW

**Comment by khanhntd** [comment]
LGTM. Consider [adding automatic create pull request](https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/) if the CodeQl or the CI is not completed too.

**Comment by jefchien** [comment]
What would go in the pull request?

**Comment by khanhntd** [comment]
Such as tagging the person who in charges of the last PR, the header and body is the same as the PR but attach the error additionally. Reason why I suggested this was skipping the manual creating PR after the workflow goes wrong.

**Comment by jefchien** [comment]
I don't think it's necessary to auto generate a PR or issue. CodeQL will already report any vulnerabilities it finds.

**Review by sethAmazon — APPROVED** [review]

**Comment by khanhntd** [comment]
LGTM.

**Review by khanhntd — APPROVED** [review]

**Pull request merged**
