### PR TITLE
bump version to v0.11.0

### PR DESCRIPTION
**Pull request by straussb**
**Description:**
Release for ADOT v0.11.0

### CODE REVIEW

**Review by mxiamxia — APPROVED** [review]
Thanks

**Review by alolita — COMMENTED** [review]
Can we change the section headers to be similar to what we use for the Collector in OTEL upstream. See https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.29.0. Would be great to see Breaking changes, Enhancements and Bug Fixes called out with related PRs listed in each section. Current format of listing closed issues and merged pull requests doesn't convey useful info to the reader. Please update. 

Please also change the title "Downloading" to Downloads and "Docker" to Download Docker image. 

Thanks!

**Comment by straussb** [comment]
Hi @alolita , yes, the polished release notes will be supplied during the release process.

**Comment by alolita** [comment]
Thanks @straussb

**Pull request merged**
