### PR TITLE
Update upstream to v0.54.0

### LINKED ISSUE #1311: Upgrade collector version to v0.54.0

### PR DESCRIPTION
**Pull request by Aneurysm9**
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>

**Link to tracking Issue:** Fixes #1311

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bryan-aguilar** [comment]
Missing updates to pkg/lambdacomponents. Are we skipping that for this PR?

**Comment by Aneurysm9** [comment]
> Missing updates to pkg/lambdacomponents. Are we skipping that for this PR?

I thought we were updating those separately, but I can do it here if it should be done now.  I think the upstream Lambda layer needs updates, too, though.

**Comment by bryan-aguilar** [comment]
> > Missing updates to pkg/lambdacomponents. Are we skipping that for this PR?
> 
> I thought we were updating those separately, but I can do it here if it should be done now. I think the upstream Lambda layer needs updates, too, though.

Historically we have been updating those dependencies at the same time. That go.mod file is just  the list of default components for the ADOT lambda layer to include so it seems reasonable to update those dependencies at the same time.

**Comment by kolanos** [comment]
@bryan-aguilar Can #1305 be included in this update by any chance?

**Pull request merged**
