### PR TITLE
Add Datadog exporter

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:**

- Add Datadog exporter to AWS OpenTelemetry distro
- Add end to end tests following wiki description
- Add exporter to README list 

**Link to tracking Issue:** n/a

**Testing:** 

- Unit tests for the component are available in the OpenTelemetry Collector contrib repository.
- End to end tests were added (see aws-observability/aws-otel-test-framework#96)

**Documentation:** 

- Added exporter to README list. I am not sure if this should be done given the description above the table; please let me know if I should not add it.
- Additional documentation is available in the OpenTelemetry Collector contrib repository

### CODE REVIEW

**Review by wyTrivail — APPROVED** [review]
thanks!

**Review by mxiamxia — APPROVED** [review]

**Comment by alolita** [comment]
@mx-psi can you please post a link to the unit tests on OpenTelemetry as well as a link to the readme here. Thanks.

**Comment by mx-psi** [comment]
@alolita sure!

- The README is available [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/datadogexporter/README.md).
- Unit tests follow the usual Go conventions and are located in the files ending with `_test.go` on the [Datadog exporter folder](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/datadogexporter) at the opentelemetry-collector-contrib repository.

I updated this PR's description with these links; hope that helps. Let me know if you need anything else.

**Comment by alolita** [comment]
Thanks @mx-psi appreciate it!

**Pull request merged**
