### PR TITLE
changed prometheus exporter in readme

### PR DESCRIPTION
**Pull request by amanbrar1999**
**Description:**

Current reference to `prometheusexporter` is misleading, this exporter defines a Prometheus pull configuration, whereas we wish to support a Prometheus push configuration using the `awsprometheusremotewriteexporter`

This component will be added to the `opentelemetry-collector-contrib` repo [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1497), before being moved into this repo

-- cc @alolita

### CODE REVIEW

**Comment by mxiamxia** [comment]
If we have decided to not support the pull mode `prometheusexporter` in aws-otel-collector. Can you also remove the `prometheusexporter` component support in the code below in this PR?

https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/defaultcomponents/defaults.go#L70

**Comment by wyTrivail** [comment]
i guess we will support pulling mode in receiver instead?

**Comment by amanbrar1999** [comment]
Yes, metrics will be received with a scrape/pull model, but we only plan to support exporting using a push model / remote write endpoints

**Comment by amanbrar1999** [comment]
Not sure why some tests seemingly related to traces are failing after removing prometheus exporter. Any ideas @wyTrivail

**Comment by amanbrar1999** [comment]
Will close this and update with the new exporter is brought in

**Pull request closed without merging**
