### PR TITLE
Add operator arm64 tests

### PR DESCRIPTION
**Pull request by erichsueh3**
**Description:** <Describe what has changed.>
This PR adds testcases to be tested by the Operator with arm64. This also adds these tests to the Operator CI

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bryan-aguilar** [comment]
My previous comment is not entirely true. The test case generator is still used for Canary tests. The Collector and Operator CI utilize the batch test generator though.

**Comment by erichsueh3** [comment]
> My previous comment is not entirely true. The python test case generator is still used for Canary tests. The Collector and Operator CI utilize the batch test generator though.

Good call, will adjust this PR to be only the change to the Operator CI

**Comment by bryan-aguilar** [comment]
This also doesn't add the necessary flags for cluster name, region, and AMP ws

**Comment by erichsueh3** [comment]
> This also doesn't add the necessary flags for cluster name, region, and AMP ws

[This comment](https://github.com/aws-observability/aws-otel-test-framework/pull/767#discussion_r932757347) explains it briefly, but we do not need to set the endpoint/cluster/region arm64 flags for the operator arm64 tests. This is because the operator arm64 cluster lives in the default region uses the default amp endpoint. The cluster is then set in the `executeTerraformTest.sh` script in a `-var=` flag, which takes precedence over all other methods of defining a terraform variable (The way non-arm64 operator tests set a cluster name is by a `.tfvars` file which has higher precedence than the default variable value from variables.tf)

**Review by bryan-aguilar — APPROVED** [review]

**Pull request merged**
