### PR TITLE
Mirror Operator images from Quay and GCR to AWS Observability ECR public gallery

### PR DESCRIPTION
**Pull request by Saber-W**
**Description:**
This PR uses and modifies a third-party repository ([docker-mirror](https://github.com/seatgeek/docker-mirror)) to mirror two repositories ([operator repo](https://quay.io/opentelemetry/opentelemetry-operator) & [kube-rbac-proxy repo](https://gcr.io/kubebuilder/kube-rbac-proxy)) to [aws-observability ECR public gallery](https://gallery.ecr.aws/aws-observability). The names of the two corresponding repositories are [adot-operator](https://gallery.ecr.aws/aws-observability/adot-operator) and [mirror-kube-rbac-proxy](https://gallery.ecr.aws/aws-observability/mirror-kube-rbac-proxy) respectively.

Every time the new version of the ADOT collector is released, we will also push the newest Operator images to AWS Observability ECR public gallery.

cc @alolita @mxiamxia

### CODE REVIEW

**Review by mxiamxia — APPROVED** [review]
Thanks! Looks the same with https://github.com/open-o11y/aws-otel-collector/pull/9/

**Comment by mxiamxia** [comment]
Hi @Saber-W, we need to setup the ADOT Operator testing in ADOT test framework. Could you help on it? I can discuss with you if you can help.

**Comment by Saber-W** [comment]
Hi @mxiamxia, yes, this one is the same with that PR which you have reviewed.

> we need to setup the ADOT Operator testing in ADOT test framework. Could you help on it?

Yes. Could you please elaborate on what testing exactly? Since this PR just mirrors the images, do you mean to write unit tests about the mirroring functions?

**Comment by mxiamxia** [comment]
d

> Hi @mxiamxia, yes, this one is the same with that PR which you have reviewed.
> 
> > we need to setup the ADOT Operator testing in ADOT test framework. Could you help on it?
> 
> Yes. Could you please elaborate on what testing exactly? Since this PR just mirrors the images, do you mean to write unit tests about the mirroring functions?

Since we're going to support ADOT Operator. I want to add ADOT Operator testing in ADOT integ test framework (for EKS) to cover at least AMP, X-Ray and CW Metric test case. So everything when a new PR sent orADOT release. The operator test case will download the Operator and apply CRD with the new ADOT Collector image with the changes and run the current test cases on those 3 types of data.
https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/terraform/eks

**Comment by Saber-W** [comment]
I understand, and we could do this end-to-end testing. I suggest setting up a meeting to further discuss this.

cc @alolita

**Pull request merged**
