### PR TITLE
Updating golang.org/x/net for v0.26.2 patch release

### PR DESCRIPTION
**Pull request by PaurushGarg**
**Description:**
Updating golang.org/x/net for v0.26.2 patch release
Cherry-picked https://github.com/aws-observability/aws-otel-collector/pull/1879 from main. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bryan-aguilar** [comment]
That cherry-pick contains changes to more than just the `/net` dependency? Is that the intended change?

**Comment by PaurushGarg** [comment]
> That cherry-pick contains changes to more than just the `/net` dependency. Is that the intended change?

I tried to update the direct dependencies that were updated in this cherry-picked commit but that didn't update the indirect dependency of `golang.org/x/net`. So I decided to cherry-pick the whole commit. Other option is to use `replace` in this go mod file. Should I choose the later option?

**Comment by bryan-aguilar** [comment]
Yes, let's try that

**Comment by PaurushGarg** [comment]
Closing this as creating a new PR for this topic: https://github.com/aws-observability/aws-otel-collector/pull/1891

**Pull request closed without merging**
