### PR TITLE
Add SignalFx Correlation trace exporter

### PR DESCRIPTION
**Pull request by tigrannajaryan**
**Description:**

- Add SignalFx Correlation trace exporter to AWS OpenTelemetry distro
- Add end to end tests following wiki description
- Add exporter to README list

**Link to tracking Issue:** n/a

**Testing:**

- Unit tests in collector contrib repository: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/signalfxcorrelationexporter
- E2E tests https://github.com/aws-observability/aws-otel-test-framework/pull/139

**Documentation:**

- Added exporter to README list
- Usage documentation: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/signalfxcorrelationexporter/README.md

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@mxiamxia @wyTrivail can you please help me understand the reason for the build failure? Looking at the build logs it appears the execution timed out, but I do not fully understsand what it was waiting for. Was the test expecting that the component will make an HTTP request to the specified mock endpoint and timed out because the request was not made?

If my understanding is correct can you please tell what exactly does the mock endpoint expect? Does it only expect that the endpoint is hit with an HTTP request, but does not validate the actual request content?

Thank you.

**Comment by wyTrivail** [comment]
@tigrannajaryan sorry for my late response.

> Was the test expecting that the component will make an HTTP request to the specified mock endpoint and timed out because the request was not made?

Yes, a https request is expected to the mock endpoint. there's a validator to call the mock endpoint as well to check if it has received data, it retries a certain times and fail if no data receiving.

> Does it only expect that the endpoint is hit with an HTTP request, but does not validate the actual request content?

Yes, It only expect receiving the https request, do no validation on the content. 

I just added a tiny doc for explaining the test and how to debug. https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/docs/run-mock-test.md, let me know if there's any issue.

**Comment by wyTrivail** [comment]
I tried to use your forked repo and run the test, and got some errors

here is the error message.

```
2020-12-01T19:21:01.622Z        WARN    signalfxcorrelationexporter@v0.15.0/correlation.go:102  Unable to determine host resource ID for correlation syncing    {"component_kind": "exporter", "component_type": "signalfx_correlation", "component_name": "signalfx_correlation"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxcorrelationexporter.(*Tracker).AddSpans.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxcorrelationexporter@v0.15.0/correlation.go:102
sync.(*Once).doSlow
        sync/once.go:66
sync.(*Once).Do
        sync/once.go:57
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxcorrelationexporter.(*Tracker).AddSpans
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxcorrelationexporter@v0.15.0/correlation.go:95
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxcorrelationexporter.(*corrExporter).pushTraceData
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxcorrelationexporter@v0.15.0/exporter.go:67
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesRequest).export
        go.opentelemetry.io/collector@v0.15.1-0.20201120151746-8ceddba7ea03/exporter/exporterhelper/tracehelper.go:53
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send
        go.opentelemetry.io/collector@v0.15.1-0.20201120151746-8ceddba7ea03/exporter/exporterhelper/common.go:222
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector@v0.15.1-0.20201120151746-8ceddba7ea03/exporter/exporterhelper/queued_retry.go:193
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
        go.opentelemetry.io/collector@v0.15.1-0.20201120151746-8ceddba7ea03/exporter/exporterhelper/tracehelper.go:114
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
        go.opentelemetry.io/collector@v0.15.1-0.20201120151746-8ceddba7ea03/exporter/exporterhelper/queued_retry.go:135
go.opentelemetry.io/collector/exporter/exporterhelper.(*traceExporter).ConsumeTraces
        go.opentelemetry.io/collector@v0.15.1-0.20201120151746-8ceddba7ea03/exporter/exporterhelper/tracehelper.go:68
go.opentelemetry.io/collector/receiver/otlpreceiver/trace.(*Receiver).sendToNextConsumer
        go.opentelemetry.io/collector@v0.15.1-0.20201120151746-8ceddba7ea03/receiver/otlpreceiver/trace/otlp.go:105
go.opentelemetry.io/collector/receiver/otlpreceiver/trace.(*Receiver).Export
        go.opentelemetry.io/collector@v0.15.1-0.20201120151746-8ceddba7ea03/receiver/otlpreceiver/trace/otlp.go:86
go.opentelemetry.io/collector/internal/data/opentelemetry-proto-gen/collector/trace/v1._TraceService_Export_Handler
        go.opentelemetry.io/collector@v0.15.1-0.20201120151746-8ceddba7ea03/internal/data/opentelemetry-proto-gen/collector/trace/v1/trace_service.pb.go:210
google.golang.org/grpc.(*Server).processUnaryRPC
        google.golang.org/grpc@v1.33.2/server.go:1210
google.golang.org/grpc.(*Server).handleStream
        google.golang.org/grpc@v1.33.2/server.go:1533
google.golang.org/grpc.(*Server).serveStreams.func1.2
        google.golang.org/grpc@v1.33.2/server.go:871

```

could this be related?

**Comment by tigrannajaryan** [comment]
@wyTrivail thank you for looking. Yes, that may be related. I will check and get back.

**Comment by tigrannajaryan** [comment]
Closing this. The component is no longer needed.

**Comment by alolita** [comment]
@tigrannajaryan confirming this exporter is no longer to be included in the upcoming release? Please confirm. Thanks!

**Comment by tigrannajaryan** [comment]
@alolita confirmed. It is no longer needed.

**Pull request closed without merging**
