### PR TITLE
Add New Relic Exporter

### PR DESCRIPTION
**Pull request by TimPansino**
**Description:**  Adds latest version of New Relic Exporter to the collector.

**Link to tracking Issue:** N/A

**Testing:** https://github.com/aws-observability/aws-otel-test-framework/pull/103

**Documentation:** N/A

### CODE REVIEW

**Review by wyTrivail — CHANGES_REQUESTED** [review]
please follow [this wiki](https://github.com/aws-observability/aws-otel-test-framework#12-create-a-pr-to-link-test-case-to-aws-otel-collector-repo) to link your test case in this PR as well, thx.

**Review by wyTrivail — APPROVED** [review]
thanks!

**Review by wyTrivail — APPROVED** [review]

**Comment by alolita** [comment]
@TimPansino Pl add a link to your OpenTelemetry unit tests and readme. Thanks.

**Comment by TimPansino** [comment]
> @TimPansino Pl add a link to your OpenTelemetry unit tests and readme. Thanks.

I've updated the description, let me know if those additions are clear and sufficient.

**Pull request merged**
