### PR TITLE
increase the workflow jobs parallel number to 10

### PR DESCRIPTION
**Pull request by mxiamxia**
**Description:** 
increase the workflow jobs parallel number to 10

### CODE REVIEW

**Review by wyTrivail — COMMENTED** [review]
why would increasing parallelism help?

**Comment by mxiamxia** [comment]
> why would increasing parallelism help?

I may not help the fix or worsen the instability issue form GithubAction, but I want to try to test it out. Do you think we should merge it after enhance the VPC and subnet IP limits? @wyTrivail

**Comment by wyTrivail** [comment]
> > why would increasing parallelism help?
> 
> I may not help the fix or worsen the instability issue form GithubAction, but I want to try to test it out. Do you think we should merge it after enhance the VPC and subnet IP limits? @wyTrivail

yes, probably wait a bit for the large vpc setting up.

**Review by wyTrivail — APPROVED** [review]
let's see...

**Pull request merged**
